### ISSUE TITLE
Travis build has been failing for some time

### ISSUE THREAD

**Issue by jyn514** [charlesdaniels/dotfiles#4]
See for example [this pull request](https://travis-ci.org/charlesdaniels/dotfiles/builds/482088502?utm_source=github_status&utm_medium=notification): several projects fail to compile because they are not portable from BSD, but travis registers it as a success. This has been going on since at least https://github.com/charlesdaniels/dotfiles/commit/6c077efd424af70cdc6fa4da6aaff03930574f08 (see https://travis-ci.org/charlesdaniels/dotfiles/builds/457134659)

**Comment by jyn514** [comment]
First time issue appears is in https://travis-ci.org/charlesdaniels/dotfiles/builds/451567231, the errors are different though

**Comment by charlesdaniels** [comment]
Should probably just disable it, as it's not doing much these days (it's a holdover from when the install process was much more complex). 

This failure is because `fastabr` requires libbsd to be present, as I find the bsd string processing functions generally preferable to the Linux (glibc) ones.
